# Generated by Django 5.2.4 on 2025-07-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apimodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
                ('unum', models.IntegerField()),
                ('uemail', models.EmailField(max_length=50)),
            ],
        ),
    ]
